name: Galactic Build and Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  galactic_build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:galactic
    steps:
      - name: Build and Test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/dependencies.repos
          package-name: easy_plan easy_plan_knowledge_base easy_plan_knowledge_graph easy_plan_val easy_plan_popf easy_plan_vhpop easy_plan_smtp easy_plan_yasmin easy_plan_bt easy_plan_tests
          target-ros2-distro: galactic
          coverage-result: false
